server:
  port: 9000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: http://47.93.123.96:8848
    gateway:
      routes[0]:
       id: system
       uri: lb://system
       predicates[0]:
         name: Path
         args[0]: /system/**
      routes[1]:
        id: generator
        uri: lb://generator
        predicates[0]:
          name: Path
          args[0]: /generator/**




